<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>1.0.6</Version>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageDescription>
    Library containing a simple hilbert based spatial index for NearestNeighbor and Within type of queries over a set of points.
    </PackageDescription>
    <PackageTags>library;spatial;geo;hilbert;C#</PackageTags>
    <PackageProjectUrl>https://github.com/bjornhandersson/com.bson</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/bjornhandersson/com.bson</RepositoryUrl>
    <Authors>bson</Authors>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
    <_Parameter1>Bson.HilbertIndex.Test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
